### ISSUE TITLE
theme and color_scheme

### ISSUE THREAD

**Issue by agjs** [sethlopezme/InspiredGitHub.tmtheme#1]
By installing and turning on the theme, only color_scheme changes. What's the markup for adding the theme as well so we have entire thing looks like on your screenshots. I can't seem to find your sublime-theme file for this theme anywhere in my packages folder.  Thanks in advance

**Comment by sethlopezme** [comment]
`tmTheme` files only affect syntax highlighting. I _am_ working on a full theme for Sublime to match the color scheme (which is partially shown in my screenshots), but it's not done yet. I'll hopefully have it up on package control in the near future.

Thank you for checking out my color scheme!

**Comment by agjs** [comment]
Really looking forward to it, what you did on your screenshots is absolutely amazing and by making it so, you would make many github fans happy. Hope to see it up soon in the future, gonna star the repo :). Thanks for the efforts!
