### ISSUE TITLE
Support for Ruby?

### ISSUE THREAD

**Issue by ddarbyson** [sethlopezme/InspiredGitHub.tmtheme#2]
Great job on matching GitHub with this colour scheme. Any future support for Ruby in the works?

**Comment by sethlopezme** [comment]
Thanks for checking out my theme!

Ruby is currently supported by this color scheme. From what I could tell, Ruby looked spot on without needing any custom syntax highlighting. Do you have any specific examples of weird Ruby highlighting with this color scheme?

**Comment by ddarbyson** [comment]
Yeah, so far so good! I was waiting for someone to finally get a colour scheme which really pairs well with GitHub. 

As for the Ruby feedback, CONSTANT is black, where it should look like the following:

``` ruby
CONSTANT = '/my/path/'
```

Plus, you could add Ruby to your README.md#Custom Language Styles if you fully support this language too.

Keep up the good work!

**Comment by sethlopezme** [comment]
Thanks for the feedback!  I'll try to have an update to the color scheme today.

Let me know if you come across any other weirdness in Ruby, and I can make those changes at the same time.

**Comment by sethlopezme** [comment]
Whoops, forgot to close this in the commit message.

f8b58ba689 should take care of this issue.
