### ISSUE TITLE
JSON looks broken

### ISSUE THREAD

**Issue by ddarbyson** [sethlopezme/InspiredGitHub.tmtheme#4]
When writing a json file, if you miss a quotation or do not close a node properly the following syntax is shown:

![screenshot 2015-06-14 20 52 20](https://cloud.githubusercontent.com/assets/1116416/8151302/9d6da07e-12d7-11e5-8036-cc4c68e05573.png)

However, when you click into the suspect node, the text in the red bounding box turns white making the text disappear on white background themes:

![screenshot 2015-06-14 20 55 32](https://cloud.githubusercontent.com/assets/1116416/8151312/e47d4e9c-12d7-11e5-9a0b-4de5e22cfca5.png)

**Comment by sethlopezme** [comment]
Unfortunately, this is an issue with the way that sublime handles syntax highlighting and isn't exclusive to JSON. The `line_highlight` background color takes precedence over the syntax background color for some reason. I've seen this happen with other themes, too. Not sure there is any fix for it, aside from changing the theme to have a different highlighting for `invalid`. I'll play around with some alternatives.

Thanks for submitting the issue, and thanks for checking out my theme!

**Comment by ddarbyson** [comment]
I really enjoy your theme, its my new default. Hope to see the JSON improve one way or another, b/c right now any small syntax error makes the text appear invisible. It's very hard to use... All the best.
