### ISSUE TITLE
Any plan to a PHPStorm version

### ISSUE THREAD

**Issue by jgrossi** [sethlopezme/InspiredGitHub.tmtheme#5]
Hey,

First thanks for this amazing theme. I'm a big fan of the GitHub theme and yours is the best one we have nowadays.

Do you have any plan for a PHPStorm version? I'd love to use this theme in that IDE as well. 

Thanks again and congrats for the project.

**Comment by sethlopezme** [comment]
Thanks for using my theme! I'm glad you're enjoying it.

I do not currently have any plan to duplicate this theme for other platforms. Feel free to create one based on this theme, though!

**Comment by jgrossi** [comment]
Hi @sethlopezme thanks for the feedback! I really appreciate that. Cheers, JG.
